### DISCUSSION TITLE
Bypass Status

### DISCUSSION THREAD

**Discussion by ChrisPotDev** [taligentx/dscKeybusInterface#240] [dscKeybusInterface Discussion]
Is there any possibility of showing the zones that are bypassed or bypassing zones without using the keypad.
Unless ive missed the code, then I do appologise.

**Comment by taligentx** [comment]
Hi @ChrisPotDev - could you provide details on how you're using the bypassed zones data?  As far as bypassing zones without the keypad, you can send the normal key sequence to bypass a zone (*1 + zone, possibly with the arming code) through the virtual keypad, `dsc.write()`.  

The library currently doesn't store the bypassed zones, this would increase memory usage and I haven't seen a home integration that can use this information.  You can access all Keybus data visible through `KeybusReader` in your sketch by using `dsc.panelData[]` - all of the currently available decoded data is laid out in `dscKeybusPrintData.cpp`.  

For example, bypassed zones 1-32 are part of the 0xA5 command:
```
  /*
   *  Zones bypassed, zones 1-32
   *
   *  Command    YYY1YYY2   MMMMDD DDDHHHHH MMMMMM    Status             CRC
   *  10100101 0 00011000 01001111 10110001 10101001 10110001 00000000 00010111 [0xA5] 2018.03.29 17:42 | Partition 1 | Zone bypassed: 2
   *  10100101 0 00011000 01001111 10110001 11000001 10110101 00000000 00110011 [0xA5] 2018.03.29 17:48 | Partition 1 | Zone bypassed: 6
   *  Byte 0   1    2        3        4        5        6        7        8
   */
  if (panelData[panelByte] >= 0xB0 && panelData[panelByte] <= 0xCF) {
    stream->print(F("Zone bypassed: "));
    printNumberOffset(panelByte, -175);
    return;
  }
```

You could check when `dsc.panelData[0] == 0xA5` and then check for the zone data.  The `Unlocker` sketch is an example of using the panel data directly in the sketch.

**Reply by ChrisPotDev** [reply]
Thank you very much @taligentx 

I occasionally need to bypass zones when not home and would just like a visual representation to ensure that I have not missed or skipped a zone.
I currently use esphome to communicate with HA.

I will look at the example youve mentioned, thank you very much.

**Reply by CJCombrink** [reply]
I also need this functionality.
I have looked at the `dscKeybusPrintData.cpp` example but not sure how to know if it is bypassed or not.
The comments only show `Zone bypassed: 2` and other fields follow the approach of a set of `restored` vs `raised` fields, for example  `Zone battery restored` and `Zone battery low` 

How would I handle what to send to my MQTT Broker?

What I have at the moment in my `loop()` function:
```
// my global state: byte bypassedZones[dscZones];

  if (dsc.panelData[0] == 0xA5) {
    if ((dsc.panelData[5] & 0x03) == 0x01) {
      //case 0x01: printPanelStatus1(6); return;
      if ((dsc.panelData[6] >= 0xB0) && (dsc.panelData[6] <= 0xCF)) {
        // printNumberOffset(panelByte, -175);
        const byte zoneNumber = dsc.panelData[6] - 0xB0; // 0 Based
        
        // Appends the mqttBypassTopic with the zone number
        char bypassPublishTopic[strlen(mqttBypassTopic) + 3];
        char zone[3];
        strcpy(bypassPublishTopic, mqttBypassTopic);
        itoa(zoneNumber + 1, zone, 10);
        strcat(bypassPublishTopic, zone);

        const byte zoneBit   = zoneNumber % 8;
        const byte zoneGroup = zoneNumber / 8;
      
        // What do I do here?
        if (bitRead(bypassedZones[zoneGroup], zoneBit)) {
          mqtt.publish(bypassPublishTopic, "1", true);            // Zone open
        }
        else {
          mqtt.publish(bypassPublishTopic, "0", true);  
        }
      }
    }
  }
```

**Comment by Dilbert66** [comment]
If you are interested, I am adding full LCD keypad emulation to my esphome implementation of this library (based on the latest "dev" branch and the HomeAssistant mqtt sketch provided by Nikhil ) .   The idea is to use a lovelace alarm panel to give the exact same capabilities as a full text LCD keypad such as allowing the ability to view open and bypassed zones, including trouble codes,etc.  It's still a work in progress but most functions are available currently. I'm sure there are still some bugs lurking but so far it's working well for me.   It's in the "new" branch of my repository here: https://github.com/Dilbert66/esphome-dsckeybus/tree/new. 
![image](https://user-images.githubusercontent.com/7193213/119353960-7e3a2c00-bc71-11eb-95bc-75f97f53d086.png)


Unfortunately, I don't have any documentation available yet so it's not useable for you at this time.  You would need to install the lovelace card and configure it first. Here's a sample of my config:
```
type: 'custom:alarm-keypad-card'
title: DSCModule_ESPHOME
unique_id: dsc1
disp_line1: sensor.dscalarmmodule_line1
disp_line2: sensor.dscalarmmodule_line2
scale: 1
service_type: esphome
service: dscalarmmodule_alarm_keypress
status_A: READY
status_B: ARMED
status_C: TROUBLE
status_D: AC
status_E: ''
status_F: ''
status_G: ''
status_H: ''
sensor_A: binary_sensor.dscalarmmodule_partition_1_ready
sensor_B: binary_sensor.dscalarmmodule_partition_1_armed
sensor_C: binary_sensor.dscalarmmodule_trouble_status
sensor_D: binary_sensor.dscalarmmodule_ac_status
button_A: STAY
button_B: AWAY
button_C: DISARM
button_D: ''
button_F: <
button_G: '>'
button_E: ''
button_H: ''
cmd_A:
  keys: /1S
cmd_B:
  keys: /1W
cmd_C:
  keys: '1234'
cmd_D:
  keys: ''
cmd_E:
  keys: A
cmd_H:
  keys: B
cmd_F:
  keys: <
cmd_G:
  keys: '>'
key_0:
  keys: '0'
key_1:
  keys: '1'
key_2:
  keys: '2'
key_3:
  keys: '3'
key_4:
  keys: '4'
key_5:
  keys: '5'
key_6:
  keys: '6'
key_7:
  keys: '7'
key_8:
  keys: '8'
key_9:
  keys: '9'
key_star:
  keys: '*'
key_pound:
  keys: '#'
beep: sensor.dscalarmmodule_beeps
view_pad: true
view_display: true
view_status: true
view_status_2: true
view_bottom: true

```
