### DISCUSSION TITLE
binary_sensor.security_partition_1  state Unknown

### DISCUSSION THREAD

**Discussion by daexpert** [taligentx/dscKeybusInterface#286] [dscKeybusInterface Discussion]
I have a 1616 alarm + arduino uno + Home Assistant, I can arm/disarm the alarm, I can read the sensors state but the problem is that the binary_sensor.security_partition_1 state is Unknown. What could be the problem?

**Comment by taligentx** [comment]
Hi @daexpert -  can you post your Home Assistant configuration.yaml?  I'm curious what part of partition 1 is configured as a `binary_sensor` component.

**Comment by daexpert** [comment]
This is the configuration.yaml section for the alarm:

alarm_control_panel:
  - platform: mqtt
    name: "Security Partition 1"
    state_topic: "dsc/Get/Partition1"
    availability_topic: "dsc/Status"
    command_topic: "dsc/Set"
    payload_disarm: "1D"
    payload_arm_home: "1S"
    payload_arm_away: "1A"
    payload_arm_night: "1N"
  - platform: mqtt
    name: "Security Partition 2"
    state_topic: "dsc/Get/Partition2"
    availability_topic: "dsc/Status"
    command_topic: "dsc/Set"
    payload_disarm: "2D"
    payload_arm_home: "2S"
    payload_arm_away: "2A"
    payload_arm_night: "2N"

binary_sensor 1:
  - platform: mqtt
    name: "Security Trouble"
    state_topic: "dsc/Get/Trouble"
    device_class: "problem"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Security Partition 1"
    state_topic: "dsc/Get/Partition1/Message"
    availability_topic: "dsc/Status"
    icon: "mdi:shield"
  - platform: mqtt
    name: "Security Partition 2"
    state_topic: "dsc/Get/Partition2/Message"
    availability_topic: "dsc/Status"
    icon: "mdi:shield"
  - platform: mqtt
    name: "Z1_Garage"
    state_topic: "dsc/Get/Zone1"
    device_class: "motion"
    payload_on: "1"
    payload_off: "0"    
  - platform: mqtt
    name: "Z2_Hol"
    state_topic: "dsc/Get/Zone2"
    device_class: "motion"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Z3_Kitchen"
    state_topic: "dsc/Get/Zone3"
    device_class: "motion"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Z4_Living Room"
    state_topic: "dsc/Get/Zone4"
    device_class: "motion"
    payload_on: "1"
    payload_off: "0"

And here is a print screen where you can see the unknown state:
![Screenshot 2022-04-06 205038](https://user-images.githubusercontent.com/78557151/162037682-e82a8e03-b391-4633-83c3-1e53b5a2f049.png)

**Reply by daexpert** [reply]
Any idea how to fix this?

**Comment by taligentx** [comment]
Hi @daexpert, this looks like a Home Assistant configuration issue - the partition status messages in your configuration are setup as `binary_sensor` components:
```
binary_sensor 1:
platform: mqtt
name: "Security Trouble"
state_topic: "dsc/Get/Trouble"
device_class: "problem"
payload_on: "1"
payload_off: "0"
name: "Security Partition 1"
state_topic: "dsc/Get/Partition1/Message"
availability_topic: "dsc/Status"
icon: "mdi:shield"
platform: mqtt
name: "Security Partition 2"
state_topic: "dsc/Get/Partition2/Message"
availability_topic: "dsc/Status"
icon: "mdi:shield"
```
This is incorrect, the status messages should be configured as `sensor` components - here's part of the configuration example from [HomeAssistant-MQTT.ino](https://github.com/taligentx/dscKeybusInterface/blob/master/examples/esp8266/HomeAssistant-MQTT/HomeAssistant-MQTT.ino):

```
# The sensor component displays the partition status message - edit the Home
# view ("Configure UI"), click "+", select the "Sensor" card, select "Entity",
# and select the security system partition.
# https://www.home-assistant.io/components/sensor.mqtt/
sensor:
  - platform: mqtt
    name: "Security Partition 1"
    state_topic: "dsc/Get/Partition1/Message"
    availability_topic: "dsc/Status"
    icon: "mdi:shield"
  - platform: mqtt
    name: "Security Partition 2"
    state_topic: "dsc/Get/Partition2/Message"
    availability_topic: "dsc/Status"
    icon: "mdi:shield"
# https://www.home-assistant.io/components/binary_sensor.mqtt/
binary_sensor:
  - platform: mqtt
    name: "Security Trouble"
    state_topic: "dsc/Get/Trouble"
    device_class: "problem"
    payload_on: "1"
    payload_off: "0"
```
