### DISCUSSION TITLE
DSC Trouble Status toggling repeatedly

### DISCUSSION THREAD

**Discussion by kghandi** [taligentx/dscKeybusInterface#287] [dscKeybusInterface Discussion]
I am using the HomeAssistant-MQTT example, and it has been working perfectly in reporting all the Zone states to HomeAssistant for months. But the Trouble Status looks strange in the HomeAssistant logbook. My DSC system has a persistent trouble flag because of old backup battery. In the HomeAssistant logbook it shows Trouble status toggling between no problem/problem. every few minutes.

```
Detected problem
11:32:07 AM - 16 minutes ago
Cleared (no problem detected)
11:32:07 AM - 16 minutes ago
Detected problem
11:28:48 AM - 20 minutes ago
Cleared (no problem detected)
11:28:48 AM - 20 minutes ago
```

I am not sure if this is a problem with dscKeybusInterface, MQTT, or HomeAssistant.
Here is the bit of code in HomeAssistant-MQTT example:
```
const char* mqttTroubleTopic = "dsc/Get/Trouble";      // Sends trouble status
```
And here is relevant bit in HomeAssistant configuration:

```
# https://www.home-assistant.io/components/alarm_control_panel.mqtt/
alarm_control_panel:
  # Security Partition 1
  - platform: mqtt
    name: "Security Partition 1"
    state_topic: "dsc/Get/Partition1"
    availability_topic: "dsc/Status"
    command_topic: "dsc/Set"
    payload_disarm: "1D"
    payload_arm_home: "1S"
    payload_arm_away: "1A"
    payload_arm_night: "1N"

# https://www.home-assistant.io/components/binary_sensor.mqtt/
binary_sensor:
  - platform: mqtt
    name: "Security Trouble"
    state_topic: "dsc/Get/Trouble"
    device_class: "problem"
    payload_on: "1"
    payload_off: "0"
```

Any ideas what might cause this?
